name: koaa
description: "A new Flutter project."


version: 1.7.2+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.3
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.3.2
  permission_handler: ^12.0.1
  countup: ^0.1.4
  intl: ^0.20.2
  flutter_animate: ^4.5.2
  flutter_secure_storage: ^10.0.0
  hive_ce: ^2.14.0
  isar_plus: ^1.2.0
  isar_plus_flutter_libs: ^1.2.0
  encrypt: ^5.0.3
  crypto: ^3.0.6
  logger: ^2.6.2
  path_provider: ^2.1.5
  fl_chart: ^1.1.1
  ml_algo: ^16.18.0
  ml_linalg: ^13.12.6
  dio: ^5.9.0
  pretty_dio_logger: ^1.4.0
  flutter_app_info: ^3.0.3
  package_info_plus: ^8.1.4
  uuid: ^4.5.1
  ml_dataframe: ^1.6.0
  flutter_local_notifications: ^19.5.0
  workmanager: ^0.9.0
  open_file: ^3.3.2
  restart_app: ^1.2.1
  local_auth: ^3.0.0
  home_widget: ^0.8.1
  file_picker: ^10.3.8
  share_plus: ^12.0.1
  wakelock_plus: ^1.3.3
  accessibility_tools: ^2.7.1
  accessibility: ^1.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.8.0
  json_serializable: ^6.10.0
  hive_ce_generator: ^1.10.0
  flutter_launcher_icons: "^0.14.4"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/
    - assets/achievements/
    - assets/subscriptions/
    - assets/hero-folder/
    - assets/patterns/
    - shorebird.yaml

flutter_icons:
  android: true
  image_path: "assets/logo.png"



