name: koaa
description: "A new Flutter project."


version: 1.0.3

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.3.2
  qr_flutter: ^4.1.0
  flutter_svg: ^2.2.1
  camera: ^0.11.2
  permission_handler: ^12.0.1
  countup: ^0.1.4
  intl: ^0.20.2
  flutter_animate: ^4.5.2
  flutter_secure_storage: ^9.2.4
  json_annotation: ^4.9.0
  hive_ce: ^2.14.0
  mobile_scanner: ^7.1.2
  encrypt: ^5.0.3
  pinput: ^5.0.2
  intl_phone_number_input: ^0.7.5
  confetti: ^0.8.0
  vibration: ^3.1.4
  logger: ^2.6.2
  path_provider: ^2.1.5
  connectivity_plus: ^6.1.1
  internet_connection_checker: ^3.0.1
  fl_chart: ^1.1.1
  ml_algo: ^16.18.0
  ml_linalg: ^13.12.6
  url_launcher: ^6.3.2
  dio: ^5.9.0
  pretty_dio_logger: ^1.4.0
  dio_cache_interceptor: ^4.0.5
  flutter_app_info: ^3.0.3
  uuid: ^4.5.1
  ml_dataframe: ^1.6.0
  lottie: ^3.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.8.0
  json_serializable: ^6.11.1
  hive_ce_generator: ^1.9.5
  flutter_launcher_icons: "^0.14.4"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/
