name: koaa
description: "A new Flutter project."


version: 1.3.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.0.5
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.3.2
  qr_flutter: ^4.1.0
  flutter_svg: ^2.2.1
  camera: ^0.11.2
  permission_handler: ^12.0.1
  countup: ^0.1.4
  intl: ^0.20.2
  flutter_animate: ^4.5.2
  flutter_secure_storage: ^10.0.0
  json_annotation: ^4.9.0
  hive_ce: ^2.14.0
  isar_plus: ^1.2.0
  isar_plus_flutter_libs: ^1.2.0
  mobile_scanner: ^7.1.4
  encrypt: ^5.0.3
  crypto: ^3.0.6
  pinput: ^6.0.1
  intl_phone_number_input: ^0.7.5
  confetti: ^0.8.0
  vibration: ^3.1.5
  logger: ^2.6.2
  path_provider: ^2.1.5
  connectivity_plus: ^6.1.1
  internet_connection_checker: ^3.0.1
  fl_chart: ^1.1.1
  ml_algo: ^16.18.0
  ml_linalg: ^13.12.6
  url_launcher: ^6.3.2
  dio: ^5.9.0
  pretty_dio_logger: ^1.4.0
  dio_cache_interceptor: ^4.0.5
  flutter_app_info: ^3.0.3
  package_info_plus: ^8.1.4
  uuid: ^4.5.1
  ml_dataframe: ^1.6.0
  lottie: ^3.3.2
  flutter_local_notifications: ^19.5.0
  workmanager: ^0.9.0
  open_file: ^3.3.2
  restart_app: ^1.2.1
  shorebird_code_push: ^2.0.0
  local_auth: ^3.0.0
  home_widget: ^0.8.1
  flutter_spinkit: ^5.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.8.0
  json_serializable: ^6.10.0
  hive_ce_generator: ^1.10.0
  flutter_launcher_icons: "^0.14.4"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/
    - assets/achievements/
    - assets/subscriptions/
    - shorebird.yaml

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"



